import { Manrope, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";
import ClientGsapProvider from "@/components/ClientGsapProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  weight: "400", // <-- especificar el peso disponible
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${manrope.variable} ${dmSerifDisplay.variable} antialiased`}>
        <ClientGsapProvider>
        <LanguageProvider>
          {children}
        </LanguageProvider>
        </ClientGsapProvider>
      </body>
    </html>
  );
}